/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Livro;


public class FormConsultaLivroTabela extends javax.swing.JFrame {

    DefaultTableModel modelo = null;
    
    
    public FormConsultaLivroTabela() {
        initComponents();
        modelo = (DefaultTableModel)jTable1.getModel();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btBsucar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        ckTodos = new javax.swing.JCheckBox();
        tfCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Livros em Acervo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icSair.png"))); // NOI18N
        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 120, 50));

        btBsucar.setBackground(new java.awt.Color(255, 255, 255));
        btBsucar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBsucar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icBuscar.png"))); // NOI18N
        btBsucar.setText(" Buscar Livro");
        btBsucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBsucarActionPerformed(evt);
            }
        });
        getContentPane().add(btBsucar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 140, 50));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icExcluir.png"))); // NOI18N
        jButton6.setText("Excluir");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 140, 50));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icAtualizar.png"))); // NOI18N
        jButton7.setText("Editar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 140, 50));

        ckTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ckTodos.setText("Buscar Todos");
        ckTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTodosActionPerformed(evt);
            }
        });
        getContentPane().add(ckTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));
        getContentPane().add(tfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Fornecedor", "Estoque", "valor", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(65);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 710, 270));

        setSize(new java.awt.Dimension(777, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBsucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBsucarActionPerformed
        limparTabela(); // limpando a tabela || Metodo criado lá em baixo
        if(ckTodos.isSelected()) // verifico se a opção de 'todos' está setada
        {            
            List<Livro> cad = new ArrayList<Livro>(); 
            cad = FormPrincipal.daoLivro.todosLivros(); //pego a lista de todos no dao
            for(Livro livro: cad) // varro a lista
            {
                inserirTabela(livro); // adicionando objeto livro do " for "            
            }
        }
        else // cada a busca seja or um objeto unico
        {            
            if(tfCodigo.getText().trim().length() != 0) //verifica-se se o codigo foi digitado
            {    
                    int codigo = Integer.parseInt(tfCodigo.getText());
                    Livro livro = FormPrincipal.daoLivro.buscarLivro(codigo); //busco o livro do codigo digitado
                    if(livro != null)
                    {
                        inserirTabela(livro); // mostrar informacoes
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Livro não encontrado!", "Atenção!", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Favor preencher o Código do Livro!", "Atenção!", JOptionPane.ERROR_MESSAGE);
                tfCodigo.requestFocus();
            }
        }
    }//GEN-LAST:event_btBsucarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
                
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ckTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTodosActionPerformed
       // habilitando e desabilitando o campo de codigo com a seleção da busca de todos
        if(ckTodos.isSelected())
            tfCodigo.setEnabled(false);
        else
        {
            tfCodigo.setEnabled(true);
            tfCodigo.requestFocus();
        }
        tfCodigo.setText("");
    }//GEN-LAST:event_ckTodosActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
                
        Livro livro = getLivro();
        
        FormLivro form = new FormLivro();
        form.livro = livro;
        form.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    
    private void limparTabela()
    {
    
        for(int i = jTable1.getRowCount() -1; i>=0; i--)
        {
            modelo.removeRow(i);
        }
               
    }
    
    private void inserirTabela(Livro livro)
    {
        
        modelo.addRow(new Object[]{livro.getCodigo(),livro.getTitulo(),
        livro.getFornecedor(),livro.getEstoque(),livro.getValor(),livro.getData()} );
        
    }
    
    private Livro getLivro()
    {
    
        int linha = jTable1.getSelectedRow(); // pega a linha selecionada
        Livro livro = new Livro(); // criando dados da linha
        
        livro.setCodigo( (Integer)jTable1.getModel().getValueAt(linha, 0) );  //pega a linha (jtable.getselectedRow)
        livro.setTitulo( (String)jTable1.getModel().getValueAt(linha, 1) );
        livro.setFornecedor( (String)jTable1.getModel().getValueAt(linha, 2) );
        livro.setEstoque( (Integer)jTable1.getModel().getValueAt(linha, 3) );
        livro.setValor( (Float)jTable1.getModel().getValueAt(linha, 4) );
        livro.setData( (String)jTable1.getModel().getValueAt(linha, 5) );
        
        
        
        return livro;
        
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivroTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivroTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivroTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultaLivroTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultaLivroTabela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBsucar;
    private javax.swing.JCheckBox ckTodos;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfCodigo;
    // End of variables declaration//GEN-END:variables
}
